print("Taller de AIPython P1 E2")
print()
print("Hola", "soy", "Franco")
print("Soy","Pamela",sep="*")
print("Arroz", "con","leche", end="?")
print("Soy otra linea")
print(120/6)
print(180//9)
print(5%2)
print(3**3)